
--  what is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount_usd) as total_revenue
FROM customer_data
GROUP BY gender;

-- which customers using discount but still spend more than the average purchase amount?
WITH
total_records AS (SELECT COUNT(*) as total FROM customer_data),
avg_amount AS (SELECT AVG(purchase_amount_usd) as avg_amount FROM customer_data),
high_average_discounted AS (SELECT COUNT(*) as high_average_discounted
                            FROM customer_data c, avg_amount a
                            WHERE c.discount_applied = 'Yes' and c.purchase_amount_usd > a.avg_amount ),
high_average_discounted_percentage  AS(SELECT h.high_average_discounted * 100 / t.total
                                        as percentage
                                        FROM high_average_discounted h, total_records t)
SELECT ROUND(hp.percentage, 2)
FROM high_average_discounted_percentage hp;

 -- what is the top 5 highest average rating products?
SELECT item_purchased, ROUND(AVG(review_rating::numeric), 2) as average_rating
FROM customer_data
GROUP BY item_purchased
ORDER BY average_rating DESC
LIMIT 5;

--comparing between average purchase amount between standard and express shipping?
SELECT DISTINCT(shipping_type)
FROM customer_data

SELECT shipping_type, COUNT(*) AS shipping_type_ranking_by_orders , ROUND(AVG(purchase_amount_usd), 2) AS avg_purchase_amount
FROM customer_data
GROUP BY shipping_type
ORDER BY shipping_type_ranking_by_orders, avg_purchase_amount DESC;

SELECT shipping_type, ROUND(AVG(purchase_amount_usd), 2) AS average_purchase_amount
FROM customer_data
GROUP BY shipping_type
ORDER BY average_purchase_amount DESC
LIMIT 2;

-- Do subscribers spend more than non-subscribers regarding the total revenue?

SELECT subscription_status, COUNT(customer_id) AS total_customer, ROUND(AVG(purchase_amount_usd), 2) AS avg_purchase, SUM(purchase_amount_usd) AS total_revenue
FROM customer_data
GROUP BY subscription_status
ORDER BY total_revenue, avg_purchase DESC;

-- top 5 products have the highest percentage of purchases with discount applied?

SELECT item_purchased AS items, discount_applied, SUM(purchase_amount_usd) AS total_purchase_amount
FROM customer_data
WHERE discount_applied = 'Yes'
GROUP BY item_purchased, discount_applied
ORDER BY total_purchase_amount DESC
LIMIT 5;
--> by discount percentage

SELECT item_purchased, ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_percentage
FROM customer_data 
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- segment the customer into new, returning, loyal based on their previous purchases and who count of them.

SELECT MIN(previous_purchases) AS min, MAX(previous_purchases) AS max,
FROM customer_data;

SELECT 
        CASE 
        WHEN previous_purchases < 16 THEN 'new_customer'
        WHEN previous_purchases >= 16 AND previous_purchases < 32 THEN 'returning_customer'
        WHEN previous_purchases >= 32 AND previous_purchases < 50 THEN 'loyal_customer'
        WHEN previous_purchases IS NULL THEN 'not defined'
        END AS customer_loyality,
        COUNT(*) AS customer_count
FROM customer_data
GROUP BY customer_loyality
ORDER BY customer_count DESC;
